FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# BoSWEmian Rhapsody (BR) API

BR is a simple API allowing consumers to get information on Artists, 
Albums, Tracks, Concerts, and Venues.

## Key

N/A = Not Available

R = Required

NR = Not Required

## Artists Collection [/artists]

### List All Artists [GET]

    You can make queries to the artists collection in order

+ Response 200 (application/json)
    
        {
            "num_results": 24, 
            "objects": [
            {
                "albums": [
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "id": 1
                }
                ], 
                "country": "United States of America", 
                "decade": "1990s / 2000s / 2010s", 
                "genre": "Alternative/Indie", 
                "id": 1, 
                "image_url": "https://i.scdn.co/image/8f037146240aad64f589b1448fcd703ba515cc24", 
                "name": "Smash Mouth", 
                "tracks": [
                {
                    "album_id": 1, 
                    "artist_id": 1, 
                    "duration": 182266, 
                    "explicit": false, 
                    "genre": "Alternative/Indie", 
                    "id": 9, 
                    "name": "Then The Morning Comes", 
                    "popularity": 34, 
                    "preview_url": "https://p.scdn.co/mp3-preview/6d91d00cdad4baeb504f65b3a944701190ac4e7f?cid=null", 
                    "release_date": "1999-01-01", 
                    "spotify_uri": "spotify:track:50MfV7a1pnOEcf2t9kobxW"
                },
                {
                    "album_id": 1, 
                    "artist_id": 1, 
                    "duration": 200373, 
                    "explicit": false, 
                    "genre": "Alternative/Indie", 
                    "id": 5, 
                    "name": "All Star", 
                    "popularity": 73, 
                    "preview_url": "https://p.scdn.co/mp3-preview/baf18743c412db2c1fcff31fac079c1c982637d2?cid=null", 
                    "release_date": "1999-01-01", 
                    "spotify_uri": "spotify:track:3cfOd4CMv2snFaKAnMdnvK"
                }
                ]
            }
            ], 
            "page": 1, 
            "total_pages": 24
        }


## Single Artist [/artists/{id}]
A single Artist object with all its details

+ Parameters
    + id (required, Number, `1`) ... Numeric `id` of the Artist to perform action with.

### Retrieve an Artist [GET]
+ Response 200 (application/json)

    + Headers

            Location: /artists/1
            
    + Body

            {
              "albums": [
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "id": 1
                }
              ], 
              "country": "United States of America", 
              "decade": "1990s / 2000s / 2010s", 
              "genre": "Alternative/Indie", 
              "id": 1, 
              "image_url": "https://i.scdn.co/image/8f037146240aad64f589b1448fcd703ba515cc24", 
              "name": "Smash Mouth", 
              "tracks": [
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 192160, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 14, 
                  "name": "Home", 
                  "popularity": 26, 
                  "preview_url": "https://p.scdn.co/mp3-preview/ec1ede504f504dd1b94ecc33fd69daba30ac9eef?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:6fg2fVOaHd2oQQEzik3PRf"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 151826, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 13, 
                  "name": "Come On, Come On", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/eadc556adf461f2cfaebe81520fb35f70036ecc0?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2iYcHbdJ7DrE0o9iOqMW8p"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 197960, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 7, 
                  "name": "Radio", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/7d94fe1314f4a36cc1a8f2cac9c974355ebf2e72?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:1poMC8EEh2mvjo9Xohwae3"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 244666, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 11, 
                  "name": "Fallen Horses", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/f13ee5759c5fa47b603aa7aa9430e36390ffce24?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:1RXThE5xrloqJud64bI3kv"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 214366, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 1, 
                  "name": "Who's There", 
                  "popularity": 29, 
                  "preview_url": "https://p.scdn.co/mp3-preview/c0ee60b1060e60ab0471d03b1db978c26eeae570?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2DDBGX5qlbBRZsAqAWfILT"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 233666, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 12, 
                  "name": "Defeat You", 
                  "popularity": 30, 
                  "preview_url": "https://p.scdn.co/mp3-preview/de62d3712201ed6f10c45e1f2a2c4405dde134b6?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:3y9l6k1sTwXgJ3L80IfrS9"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 221360, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 3, 
                  "name": "I Just Wanna See", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/d633a56081d6bf6ddc0897996506aef45f452763?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:4R4HHwbrMb4Fttzrfccmh7"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 189093, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 2, 
                  "name": "Diggin' Your Scene", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/53ee7796c25dd4da75b9618de2002fce57af2c65?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:5VL3c4UjMFR8BcPqoFVTNc"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 151106, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 10, 
                  "name": "Road Man", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/7d9f5f8c417560fa80af363f2faf3ad88f7314df?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:50uYYNVsBYbg8ZuGWN3JSd"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 217866, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 6, 
                  "name": "Satellite", 
                  "popularity": 32, 
                  "preview_url": "https://p.scdn.co/mp3-preview/874d9cf96ef76b6234f9ea1c19260496d8216007?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:7E6bQMVRpYsM8oDhha3nv8"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 205200, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 4, 
                  "name": "Waste", 
                  "popularity": 33, 
                  "preview_url": "https://p.scdn.co/mp3-preview/5bfed88deb512812d1b9e6b9d8c8aa07edbbe3df?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2Wo9IRlgSTeQs76VuuYnpw"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 182266, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 9, 
                  "name": "Then The Morning Comes", 
                  "popularity": 34, 
                  "preview_url": "https://p.scdn.co/mp3-preview/6d91d00cdad4baeb504f65b3a944701190ac4e7f?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:50MfV7a1pnOEcf2t9kobxW"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 248293, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 8, 
                  "name": "Stoned", 
                  "popularity": 38, 
                  "preview_url": "https://p.scdn.co/mp3-preview/4e0d598a6fe24c0e66d592fdb619e156674a56c3?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:7bFstEkOysInloEcaHzMUM"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 150773, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 15, 
                  "name": "Can't Get Enough Of You Baby", 
                  "popularity": 46, 
                  "preview_url": "https://p.scdn.co/mp3-preview/3833bb556769e584e21ef8f31b34ea86ee953419?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:0UVIXwqfTjefBbDyY60MWB"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 200373, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 5, 
                  "name": "All Star", 
                  "popularity": 73, 
                  "preview_url": "https://p.scdn.co/mp3-preview/baf18743c412db2c1fcff31fac079c1c982637d2?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:3cfOd4CMv2snFaKAnMdnvK"
                }
              ]
            }

## Albums Collection [/albums]

### List All Albums [GET]

    You can make queries to the albums collection 

+ Response 200 (application/json)

        {
            "num_results": 24, 
            "objects": [
            {
              "album_cover_url": "https://i.scdn.co/image/ede1f1d01b8024ef1f9ae3fea1b25bfe083783bd", 
              "artists": [
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "id": 1
                }
              ], 
              "genre": "Alternative/Indie", 
              "id": 1, 
              "label": "Interscope", 
              "name": "Astro Lounge", 
              "number_of_tracks": 15, 
              "release_date": "1999-01-01", 
              "spotify_uri": "spotify:album:2kyTLcEZe6nc1s6ve0zW9P", 
              "tracks": [
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 192160, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 14, 
                  "name": "Home", 
                  "popularity": 26, 
                  "preview_url": "https://p.scdn.co/mp3-preview/ec1ede504f504dd1b94ecc33fd69daba30ac9eef?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:6fg2fVOaHd2oQQEzik3PRf"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 151826, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 13, 
                  "name": "Come On, Come On", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/eadc556adf461f2cfaebe81520fb35f70036ecc0?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2iYcHbdJ7DrE0o9iOqMW8p"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 197960, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 7, 
                  "name": "Radio", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/7d94fe1314f4a36cc1a8f2cac9c974355ebf2e72?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:1poMC8EEh2mvjo9Xohwae3"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 244666, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 11, 
                  "name": "Fallen Horses", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/f13ee5759c5fa47b603aa7aa9430e36390ffce24?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:1RXThE5xrloqJud64bI3kv"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 214366, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 1, 
                  "name": "Who's There", 
                  "popularity": 29, 
                  "preview_url": "https://p.scdn.co/mp3-preview/c0ee60b1060e60ab0471d03b1db978c26eeae570?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2DDBGX5qlbBRZsAqAWfILT"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 233666, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 12, 
                  "name": "Defeat You", 
                  "popularity": 30, 
                  "preview_url": "https://p.scdn.co/mp3-preview/de62d3712201ed6f10c45e1f2a2c4405dde134b6?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:3y9l6k1sTwXgJ3L80IfrS9"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 221360, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 3, 
                  "name": "I Just Wanna See", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/d633a56081d6bf6ddc0897996506aef45f452763?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:4R4HHwbrMb4Fttzrfccmh7"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 189093, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 2, 
                  "name": "Diggin' Your Scene", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/53ee7796c25dd4da75b9618de2002fce57af2c65?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:5VL3c4UjMFR8BcPqoFVTNc"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 151106, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 10, 
                  "name": "Road Man", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/7d9f5f8c417560fa80af363f2faf3ad88f7314df?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:50uYYNVsBYbg8ZuGWN3JSd"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 217866, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 6, 
                  "name": "Satellite", 
                  "popularity": 32, 
                  "preview_url": "https://p.scdn.co/mp3-preview/874d9cf96ef76b6234f9ea1c19260496d8216007?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:7E6bQMVRpYsM8oDhha3nv8"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 205200, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 4, 
                  "name": "Waste", 
                  "popularity": 33, 
                  "preview_url": "https://p.scdn.co/mp3-preview/5bfed88deb512812d1b9e6b9d8c8aa07edbbe3df?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2Wo9IRlgSTeQs76VuuYnpw"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 182266, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 9, 
                  "name": "Then The Morning Comes", 
                  "popularity": 34, 
                  "preview_url": "https://p.scdn.co/mp3-preview/6d91d00cdad4baeb504f65b3a944701190ac4e7f?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:50MfV7a1pnOEcf2t9kobxW"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 248293, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 8, 
                  "name": "Stoned", 
                  "popularity": 38, 
                  "preview_url": "https://p.scdn.co/mp3-preview/4e0d598a6fe24c0e66d592fdb619e156674a56c3?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:7bFstEkOysInloEcaHzMUM"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 150773, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 15, 
                  "name": "Can't Get Enough Of You Baby", 
                  "popularity": 46, 
                  "preview_url": "https://p.scdn.co/mp3-preview/3833bb556769e584e21ef8f31b34ea86ee953419?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:0UVIXwqfTjefBbDyY60MWB"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 200373, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 5, 
                  "name": "All Star", 
                  "popularity": 73, 
                  "preview_url": "https://p.scdn.co/mp3-preview/baf18743c412db2c1fcff31fac079c1c982637d2?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:3cfOd4CMv2snFaKAnMdnvK"
                }
              ]
            }
            ], 
          "page": 1, 
          "total_pages": 24
          }



## Single Album [/albums/{id}]
A single Album object with all its details

+ Parameters
    + id (required, Number, `1`) ... Numeric `id` of the Album to perform action with.

### Retrieve an Album [GET]
+ Response 200 (application/json)

    + Headers

            Location: /albums/1
            
    + Body

            {
              "album_cover_url": "https://i.scdn.co/image/ede1f1d01b8024ef1f9ae3fea1b25bfe083783bd", 
              "artists": [
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "id": 1
                }
              ], 
              "genre": "Alternative/Indie", 
              "id": 1, 
              "label": "Interscope", 
              "name": "Astro Lounge", 
              "number_of_tracks": 15, 
              "release_date": "1999-01-01", 
              "spotify_uri": "spotify:album:2kyTLcEZe6nc1s6ve0zW9P", 
              "tracks": [
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 192160, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 14, 
                  "name": "Home", 
                  "popularity": 26, 
                  "preview_url": "https://p.scdn.co/mp3-preview/ec1ede504f504dd1b94ecc33fd69daba30ac9eef?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:6fg2fVOaHd2oQQEzik3PRf"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 151826, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 13, 
                  "name": "Come On, Come On", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/eadc556adf461f2cfaebe81520fb35f70036ecc0?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2iYcHbdJ7DrE0o9iOqMW8p"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 197960, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 7, 
                  "name": "Radio", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/7d94fe1314f4a36cc1a8f2cac9c974355ebf2e72?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:1poMC8EEh2mvjo9Xohwae3"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 244666, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 11, 
                  "name": "Fallen Horses", 
                  "popularity": 28, 
                  "preview_url": "https://p.scdn.co/mp3-preview/f13ee5759c5fa47b603aa7aa9430e36390ffce24?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:1RXThE5xrloqJud64bI3kv"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 214366, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 1, 
                  "name": "Who's There", 
                  "popularity": 29, 
                  "preview_url": "https://p.scdn.co/mp3-preview/c0ee60b1060e60ab0471d03b1db978c26eeae570?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2DDBGX5qlbBRZsAqAWfILT"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 233666, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 12, 
                  "name": "Defeat You", 
                  "popularity": 30, 
                  "preview_url": "https://p.scdn.co/mp3-preview/de62d3712201ed6f10c45e1f2a2c4405dde134b6?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:3y9l6k1sTwXgJ3L80IfrS9"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 221360, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 3, 
                  "name": "I Just Wanna See", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/d633a56081d6bf6ddc0897996506aef45f452763?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:4R4HHwbrMb4Fttzrfccmh7"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 189093, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 2, 
                  "name": "Diggin' Your Scene", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/53ee7796c25dd4da75b9618de2002fce57af2c65?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:5VL3c4UjMFR8BcPqoFVTNc"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 151106, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 10, 
                  "name": "Road Man", 
                  "popularity": 31, 
                  "preview_url": "https://p.scdn.co/mp3-preview/7d9f5f8c417560fa80af363f2faf3ad88f7314df?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:50uYYNVsBYbg8ZuGWN3JSd"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 217866, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 6, 
                  "name": "Satellite", 
                  "popularity": 32, 
                  "preview_url": "https://p.scdn.co/mp3-preview/874d9cf96ef76b6234f9ea1c19260496d8216007?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:7E6bQMVRpYsM8oDhha3nv8"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 205200, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 4, 
                  "name": "Waste", 
                  "popularity": 33, 
                  "preview_url": "https://p.scdn.co/mp3-preview/5bfed88deb512812d1b9e6b9d8c8aa07edbbe3df?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:2Wo9IRlgSTeQs76VuuYnpw"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 182266, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 9, 
                  "name": "Then The Morning Comes", 
                  "popularity": 34, 
                  "preview_url": "https://p.scdn.co/mp3-preview/6d91d00cdad4baeb504f65b3a944701190ac4e7f?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:50MfV7a1pnOEcf2t9kobxW"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 248293, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 8, 
                  "name": "Stoned", 
                  "popularity": 38, 
                  "preview_url": "https://p.scdn.co/mp3-preview/4e0d598a6fe24c0e66d592fdb619e156674a56c3?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:7bFstEkOysInloEcaHzMUM"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 150773, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 15, 
                  "name": "Can't Get Enough Of You Baby", 
                  "popularity": 46, 
                  "preview_url": "https://p.scdn.co/mp3-preview/3833bb556769e584e21ef8f31b34ea86ee953419?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:0UVIXwqfTjefBbDyY60MWB"
                }, 
                {
                  "album_id": 1, 
                  "artist_id": 1, 
                  "duration": 200373, 
                  "explicit": false, 
                  "genre": "Alternative/Indie", 
                  "id": 5, 
                  "name": "All Star", 
                  "popularity": 73, 
                  "preview_url": "https://p.scdn.co/mp3-preview/baf18743c412db2c1fcff31fac079c1c982637d2?cid=null", 
                  "release_date": "1999-01-01", 
                  "spotify_uri": "spotify:track:3cfOd4CMv2snFaKAnMdnvK"
                }
              ]
            }

## Tracks Collection [/tracks]

### List All Tracks [GET]

    You can make queries to the tracks collection 

+ Response 200 (application/json)

        {
          "num_results": 347, 
          "objects": [
            {
              "album": {
                "album_cover_url": "https://i.scdn.co/image/ede1f1d01b8024ef1f9ae3fea1b25bfe083783bd", 
                "genre": "Alternative/Indie", 
                "id": 1, 
                "label": "Interscope", 
                "name": "Astro Lounge", 
                "number_of_tracks": 15, 
                "release_date": "1999-01-01", 
                "spotify_uri": "spotify:album:2kyTLcEZe6nc1s6ve0zW9P"
              }, 
              "album_id": 1, 
              "artist": {
                "country": "United States of America", 
                "decade": "1990s / 2000s / 2010s", 
                "genre": "Alternative/Indie", 
                "id": 1, 
                "image_url": "https://i.scdn.co/image/8f037146240aad64f589b1448fcd703ba515cc24", 
                "name": "Smash Mouth"
              }, 
              "artist_id": 1, 
              "duration": 214366, 
              "explicit": false, 
              "genre": "Alternative/Indie", 
              "id": 1, 
              "name": "Who's There", 
              "popularity": 29, 
              "preview_url": "https://p.scdn.co/mp3-preview/c0ee60b1060e60ab0471d03b1db978c26eeae570?cid=null", 
              "release_date": "1999-01-01", 
              "spotify_uri": "spotify:track:2DDBGX5qlbBRZsAqAWfILT"
            }
          ], 
          "page": 1, 
          "total_pages": 347
        }

## Single Track [/tracks/{id}]
A single Track object with all its details

+ Parameters
    + id (required, Number, `1`) ... Numeric `id` of the Track to perform action with.

### Retrieve a Track [GET]
+ Response 200 (application/json)

    + Headers

            Location: /tracks/1
            
    + Body

            {
              "album": {
                "album_cover_url": "https://i.scdn.co/image/ede1f1d01b8024ef1f9ae3fea1b25bfe083783bd", 
                "genre": "Alternative/Indie", 
                "id": 1, 
                "label": "Interscope", 
                "name": "Astro Lounge", 
                "number_of_tracks": 15, 
                "release_date": "1999-01-01", 
                "spotify_uri": "spotify:album:2kyTLcEZe6nc1s6ve0zW9P"
              }, 
              "album_id": 1, 
              "artist": {
                "country": "United States of America", 
                "decade": "1990s / 2000s / 2010s", 
                "genre": "Alternative/Indie", 
                "id": 1, 
                "image_url": "https://i.scdn.co/image/8f037146240aad64f589b1448fcd703ba515cc24", 
                "name": "Smash Mouth"
              }, 
              "artist_id": 1, 
              "duration": 214366, 
              "explicit": false, 
              "genre": "Alternative/Indie", 
              "id": 1, 
              "name": "Who's There", 
              "popularity": 29, 
              "preview_url": "https://p.scdn.co/mp3-preview/c0ee60b1060e60ab0471d03b1db978c26eeae570?cid=null", 
              "release_date": "1999-01-01", 
              "spotify_uri": "spotify:track:2DDBGX5qlbBRZsAqAWfILT"
            }

## Concerts Collection [/concerts]

### List All Concerts [GET]

    You can make queries to the concert collection 

+ Response 200 (application/json)

        {
          "num_results": 1091, 
          "objects": [
            {
              "artist_album_pairs": [
                {
                  "aa_id": 1, 
                  "concert_id": 1, 
                  "id": 1
                }
              ], 
              "date": "2017-05-13", 
              "event_link": "http://www.bandsintown.com/event/13940407?app_id=boswemianrhapsody&artist=Smash+Mouth&came_from=67", 
              "id": 1, 
              "name": "Smash Mouth", 
              "time": "19:00:00", 
              "venue": {
                "city": "Peachtree City", 
                "country": "United States", 
                "id": 1, 
                "latitude": 33.384111, 
                "longitude": -84.57109, 
                "name": "THE FRED ", 
                "region": "GA"
              }, 
              "venue_id": 1
            }, 
          ], 
          "page": 1, 
          "total_pages": 122
        }

## Single Concert [/concerts/{id}]
A single Concert object with all its details

+ Parameters
    + id (required, Number, `1`) ... Numeric `id` of the Concert to perform action with.

### Retrieve a Concert [GET]
+ Response 200 (application/json)

    + Headers

            Location: /concerts/1
            
    + Body

            {
              "artist_album_pairs": [
                {
                  "aa_id": 1, 
                  "concert_id": 1, 
                  "id": 1
                }
              ], 
              "date": "2017-05-13", 
              "event_link": "http://www.bandsintown.com/event/13940407?app_id=boswemianrhapsody&artist=Smash+Mouth&came_from=67", 
              "id": 1, 
              "name": "Smash Mouth", 
              "time": "19:00:00", 
              "venue": {
                "city": "Peachtree City", 
                "country": "United States", 
                "id": 1, 
                "latitude": 33.384111, 
                "longitude": -84.57109, 
                "name": "THE FRED ", 
                "region": "GA"
              }, 
              "venue_id": 1
            }

## Venues Collection [/venues]

### List All Venues [GET]

    You can make queries to the venues collection 

+ Response 200 (application/json)

        {
          "num_results": 84, 
          "objects": [
            {
              "city": "Peachtree City", 
              "concerts": [
                {
                  "date": "2017-05-13", 
                  "event_link": "http://www.bandsintown.com/event/13940407?app_id=boswemianrhapsody&artist=Smash+Mouth&came_from=67", 
                  "id": 1, 
                  "name": "Smash Mouth", 
                  "time": "19:00:00", 
                  "venue_id": 1
                }
              ], 
              "country": "United States", 
              "id": 1, 
              "latitude": 33.384111, 
              "longitude": -84.57109, 
              "name": "THE FRED ", 
              "region": "GA"
            } 
          ], 
          "page": 1, 
          "total_pages": 84
        }

## Single Venue [/venues/{id}]
A single Venue object with all its details

+ Parameters
    + id (required, Number, `1`) ... Numeric `id` of the Venue to perform action with.

### Retrieve a Venue [GET]
+ Response 200 (application/json)

    + Headers

            Location: /venues/1
            
    + Body

            {
              "city": "Peachtree City", 
              "concerts": [
                {
                  "date": "2017-05-13", 
                  "event_link": "http://www.bandsintown.com/event/13940407?app_id=boswemianrhapsody&artist=Smash+Mouth&came_from=67", 
                  "id": 1, 
                  "name": "Smash Mouth", 
                  "time": "19:00:00", 
                  "venue_id": 1
                }
              ], 
              "country": "United States", 
              "id": 1, 
              "latitude": 33.384111, 
              "longitude": -84.57109, 
              "name": "THE FRED ", 
              "region": "GA"
            }